id: 178d7059-96bb-4a2e-8efd-9c50ea36e6f7
version: 4
name: Test playbook2
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 36a728cd-3e39-4cf9-8f3a-7bce679e9cb4
    type: start
    task:
      id: 36a728cd-3e39-4cf9-8f3a-7bce679e9cb4
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 8b96e4d4-1364-4a4c-83cf-82d9d698c831
    type: regular
    task:
      id: 8b96e4d4-1364-4a4c-83cf-82d9d698c831
      version: -1
      name: Untitled Task
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 670,
          "y": 390
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: ddfc5344-36fc-436c-8ccc-f713e27461a7
    type: regular
    task:
      id: ddfc5344-36fc-436c-8ccc-f713e27461a7
      version: -1
      name: Untitled Task
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 310,
          "y": 520
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: 11b3ee7f-b9f3-4b7e-8f2b-de884fe01b2c
    type: regular
    task:
      id: 11b3ee7f-b9f3-4b7e-8f2b-de884fe01b2c
      version: -1
      name: Untitled Task
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 820,
          "y": 690
        }
      }
    note: false
    timertriggers: []
  "4":
    id: "4"
    taskid: b1492455-10af-40a0-85d9-80576a56a5a5
    type: regular
    task:
      id: b1492455-10af-40a0-85d9-80576a56a5a5
      version: -1
      name: Untitled Task
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 300,
          "y": 620
        }
      }
    note: false
    timertriggers: []
  "5":
    id: "5"
    taskid: b79ca52d-d416-46b3-8d92-32bc00d64f0c
    type: regular
    task:
      id: b79ca52d-d416-46b3-8d92-32bc00d64f0c
      version: -1
      name: Untitled Task
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 190,
          "y": 420
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 1010,
        "x": 190,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
